version: '3.8'
services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
#    restart: always
    ports:
      - 51883:1972
      - 52883:52773
      - 53773
    command:
      - --check-caps false --ISCAgent false
      - -a
      - iris session iris -U%SYS '##class(Security.Users).UnExpireUserPasswords("*")'
    volumes:
    #  - ~/iris.key:/usr/irissys/mgr/iris.key
      - ./:/irisdev/app
